version: '3.8'

services:
  deepseek-ocr-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: deepseek-ocr-vllm:latest
    container_name: deepseek-ocr-api
    
    # GPU support
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    
    # Port mapping
    ports:
      - "8000:8000"
    
    # Environment variables
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - WORKERS=1
      - LOG_LEVEL=INFO
      - VLLM_USE_V1=1
      - CUDA_VISIBLE_DEVICES=0  # Specify which GPU to use
    
    # Volumes
    volumes:
      # Mount model directory (change to your local model path)
      - ./DeepSeek-OCR-vllm/models:/app/models:ro
      # Optionally mount config for easy updates
      - ./DeepSeek-OCR-vllm/config.py:/app/config.py:ro
    
    # Restart policy
    restart: unless-stopped
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    
    # Shared memory size (important for PyTorch)
    shm_size: '8gb'
    
    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

